/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class ClientGUI extends javax.swing.JFrame {
    private static Client client;

    /**
     * Creates new form Client
     */
    private ClientGUI() {
        Object[] possibleType={"WASHING MACHINE [240w]","FRIDGE [305w]","LIGHT BULB [150w]","THERMOSTAT [750w]","OVEN [1500w]","FISH TANK [400w]","TV [150w]"};
        String type =(String) JOptionPane.showInputDialog(null,"Possible Type", "Choose",JOptionPane.QUESTION_MESSAGE,null,possibleType,"TV");
        if(type != null) {
            int id = setID(type)[0];
            int kw = setID(type)[1];

            initComponents();
            client = new Client(this, id, kw, type);
            new Thread(client).start();
            OffButton.setSelected(true);

            OnButton.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    setState("WAITING FOR DISCOVERY FROM THE SERVER!");
                }
            });

            this.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    client.stopProtocol();
                }
            });
        }
        else{
            System.exit(0);
        }
    }

    boolean checkONPower(){ return !OffButton.isSelected();}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnOffGroup = new javax.swing.ButtonGroup();
        jServerInformation = new javax.swing.JLabel();
        jClientInformation = new javax.swing.JLabel();
        jState = new javax.swing.JLabel();
        OnButton = new javax.swing.JRadioButton();
        OffButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jServerInformation.setText("Server");

        jClientInformation.setText("Device");

        jState.setText("State");

        OnOffGroup.add(OnButton);
        OnButton.setText("ON");

        OnOffGroup.add(OffButton);
        OffButton.setText("OFF");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jServerInformation, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jClientInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jState)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(OnButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(OffButton)
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jServerInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jClientInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnButton)
                    .addComponent(OffButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClientGUI().setVisible(true));
    }
    /**
     * This method is used by client.java to set the information about the Device
     * @param s 
     */

    void setClient(String s){
        jClientInformation.setText(s);
    }
    
    /**
     * This method is used by client.java to set the information about the Server
     * @param s 
     */
    
    public void setServer(String s){
        jServerInformation.setText(s);
    }
    
    /**
     * This method is used by client.java to set the information about the Device state
     * @param s 
     */
    

    public void setState(String s){
        jState.setText(s);
    }
    
    public void setTextArea(String s){
        jTextArea1.append(s);
    }

    /**
     * Set the typeID number and kw corresponding to the type of client selected
     * @param type the type of client selected
     * @return v[0] is a typeID while v[1] is the kW
     */
    private static int[] setID(String type){
        int[] v = new int[2];
        switch(type){
            case "WASHING MACHINE [240w]": v[0]=0; v[1]=240;break;
            case "FRIDGE [305w]": v[0]=1;v[1]=305;break;
            case "LIGHT BULB [150w]":v[0]=2;v[1]=150;break; //All the lighting
            case "THERMOSTAT [750w]": v[0]=3;v[1]=750;break;
            case "OVEN [1500w]":v[0]=4;v[1]=1500;break;
            case "FISH TANK [400w]":v[0]=5;v[1]=400;break;
            case "TV [150w]":v[0]=6;v[1]=150;break;
            default : v[0]=-1;v[1]=0;
        }
        return v;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OffButton;
    private javax.swing.JRadioButton OnButton;
    private javax.swing.ButtonGroup OnOffGroup;
    private javax.swing.JLabel jClientInformation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jServerInformation;
    private javax.swing.JLabel jState;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
