package Server;

import javax.swing.*;
import java.awt.*;
import java.util.Collection;

import static Commons.Constants.*;

public class ServerGUI {
    private JTextArea infoPanel;
    private JPanel mainFrame;
    private Server server;

    private static JFrame frame;

    public ServerGUI() {
        server = new Server(this);
        new Thread(server).start();
    }

    /**
     * GUI main
     *
     * @param args args
     */
    public static void main(String[] args) {
        frame = new JFrame("ServerGUI");
        frame.setContentPane(new ServerGUI().mainFrame);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setResizable(false);
    }

    public void updateDevices(Collection<Device> devices) {
        infoPanel.setText("");
        String tmp = "";
        for (Device d : devices) {
            tmp += parseType(d.getType()) + ":\n\tLast confirm: " + d.getLastCommunication() + "\n\tLast value sent: " + parseValue(d.getLastValueSent()) + "\n\n";
        }
        infoPanel.setText(tmp);
    }

    private String parseValue(Integer value) {
        if (value == null) return "No value sent!";
        return value.toString();
    }

    private String parseType(int type) {
        switch (type) {
            case WASHING_MACHINE:
                return "Washing Machine";

            case FRIDGE:
                return "Fridge";

            case LIGHT_BULB:
                return "Light bulb";

            case THERMOSTAT:
                return "Thermostat";

            case OVEN:
                return "Oven";

            case FISH_TANK:
                return "Fish tank";

            case TV:
                return "TV";

            default:
                return "Device";
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainFrame = new JPanel();
        mainFrame.setLayout(new GridBagLayout());
        mainFrame.setFocusTraversalPolicyProvider(false);
        mainFrame.setFocusable(true);
        mainFrame.setMinimumSize(new Dimension(300, 300));
        mainFrame.setPreferredSize(new Dimension(600, 300));
        final JScrollPane scrollPane1 = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainFrame.add(scrollPane1, gbc);
        infoPanel = new JTextArea();
        infoPanel.setMinimumSize(new Dimension(575, 275));
        infoPanel.setPreferredSize(new Dimension(575, 275));
        scrollPane1.setViewportView(infoPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainFrame;
    }

}
